const productRoute = require('./product.route')
const homeRoute = require('./home.route')
const categoryRoute = require('./category.route')
const searchRoute = require('./search.route')
const cartRoute = require('./cart.route')
const checkoutRoute = require('./checkout.route')
const userRoute = require('./user.route')
const getCategoryTree = require("../../middleware/client/category.middleware")
const cart = require("../../middleware/client/cart.middleware")
const user = require("../../middleware/client/user.middleware")
const setting = require("../../middleware/client/setting.middleware")

module.exports = (app) => {
    app.use(getCategoryTree.category)
    app.use(cart.cartId)
    app.use(setting.settingGeneral)
    app.use(user.user)
    app.use('/', homeRoute)
    app.use('/cart', cartRoute)
    app.use('/category' ,categoryRoute)
    app.use('/search' ,searchRoute)
    app.use('/product' ,productRoute)
    app.use('/checkout' ,checkoutRoute)
    app.use('/user' ,userRoute)
}